import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { FileText, ChevronDown, History, Info } from 'lucide-react';

interface PlanViewerProps {
    filename: string;
    content: string;
}

const PlanViewer: React.FC<PlanViewerProps> = ({ filename, content }) => {
    return (
        <div className="h-full bg-[#0d1117] flex flex-col overflow-hidden text-[#e6edf3]">
            {/* Header / Tab-like Bar - Similar to the image */}
            <div className="flex items-center justify-between px-6 py-4 border-b border-[#30363d] bg-[#0d1117]/80 backdrop-blur-sm sticky top-0 z-10">
                <div className="flex flex-col gap-1">
                    <div className="flex items-center gap-2 text-[var(--text-muted)] text-xs">
                        <History className="w-3.5 h-3.5" />
                        <span>Implementation Plan</span>
                        <span className="opacity-50">•</span>
                        <span>Just now</span>
                    </div>
                    <div className="flex items-center gap-3">
                        <FileText className="w-5 h-5 text-[#3fb950]" />
                        <h1 className="text-xl font-bold tracking-tight text-[#f0f6fc]">{filename}</h1>
                    </div>
                </div>

                <div className="flex items-center gap-2">
                    <button className="flex items-center gap-2 bg-[#21262d] hover:bg-[#30363d] text-[#c9d1d9] px-3.5 py-1.5 rounded-lg border border-[#30363d] text-sm font-semibold transition-all shadow-sm">
                        <span>Review</span>
                        <ChevronDown className="w-4 h-4" />
                    </button>
                </div>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto custom-scrollbar p-10 md:p-14 lg:p-20 bg-[#0d1117]">
                <div className="max-w-4xl mx-auto">
                    <div className="prose prose-invert prose-emerald max-w-none 
                        prose-headings:font-bold prose-headings:tracking-tight prose-headings:border-b-0
                        prose-h1:text-[2.75rem] prose-h1:mb-12 prose-h1:leading-tight prose-h1:text-[#f0f6fc]
                        prose-h2:text-2xl prose-h2:mt-16 prose-h2:mb-6 prose-h2:text-[#f0f6fc]
                        prose-h3:text-xl prose-h3:mt-10 prose-h3:mb-4 prose-h3:text-[#f0f6fc]
                        prose-p:text-[#9198a1] prose-p:leading-relaxed prose-p:text-lg
                        prose-li:text-[#9198a1] prose-li:my-2 prose-li:text-lg
                        prose-strong:text-[#f0f6fc] prose-strong:font-bold
                        prose-code:text-[#79c0ff] prose-code:bg-[#161b22] prose-code:px-2 prose-code:py-1 prose-code:rounded prose-code:before:content-none prose-code:after:content-none prose-code:font-mono
                        prose-pre:bg-[#161b22] prose-pre:border prose-pre:border-[#30363d] prose-pre:rounded-xl prose-pre:p-6
                        prose-blockquote:border-l-4 prose-blockquote:border-l-[#30363d] prose-blockquote:text-[#8b949e] prose-blockquote:italic
                    ">
                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                            {content}
                        </ReactMarkdown>
                    </div>

                    {/* Bottom Meta Info */}
                    <div className="mt-20 pt-10 border-t border-[#30363d] flex items-center gap-3 text-sm text-[#8b949e]">
                        <Info className="w-5 h-5 opacity-70" />
                        <p className="font-medium italic">This implementation plan was generated by CodeRefine AI for your review. Choose "Execute" in the chat to apply these changes.</p>
                    </div>
                </div>
            </div>


        </div>
    );
};

export default PlanViewer;
